Lint/UnusedMethodArgument:
  AutoCorrect: false

Metrics/AbcSize:
  Max: 21

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  Max: 20

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  AutoCorrect: false
